STRINGS = {
    'UKRAINE': {
        'column_added': "✅ Колонку '{column_name}' додано до таблиці '{table_name}'!",
        'error_adding_column': "⚠️ Помилка додавання колонки {column_name} до {table_name}: {e}",
        'shipping_label_ukraine': "Доставка:",
        'receipt': (
            "👤 <b>Клієнт:</b> {user_name}\n\n"
            "📧 <b>Email:</b> {email}\n\n"
            "📞 <b>Телефон:</b> {phone}\n\n"
            "📍 <b>{shipping_label}</b> {address}\n\n"
            "💳 <b>Оплата:</b> {payment}\n\n"
            "📦 <b>Товари:</b>\n{products_text}\n"
            "💰 <b>Всього: {total}{symbol}</b>\n\n"
            "🕐 <b>Дата:</b> {date}\n\n"
            "Дякуємо за покупку! 🛍️"
        ),
        'product': "Товар",
        'price_calculation_error': "Помилка розрахунку ціни: {e}",
        'size_variant': "📏 Розмір (S, M, L)",
        'color_variant': "🎨 Колір",
        'memory_variant': "💾 Пам'ять (GB)",
        'volume_variant': "🥛 Об'єм (L, ml)",
        'weight_variant': "⚖️ Вага (kg, g)",
        'shoe_size_variant': "👟 Розмір взуття",
        'finish_skip_variant': "✅ Завершити / Пропустити",
        'user_blocked': "Вас заблоковано у цьому боті.",
        'user_blocked_inline': "Вас заблоковано у цьому боті.",
        'invalid_request': "❌ Неправильний запит",
        'order_already_delivered_or_canceled': "❌ Замовлення вже доставлено або скасовано",
        'customer_canceled_order': "🔴 Клієнт скасував замовлення. #{order_id}",
        'order_canceled': "✅ Замовлення скасовано",
        'my_cart_count': "🛒 Мій кошик ({cart_count})",
        'my_cart': "🛒 Мій кошик",
        'admin_panel_button': "👑 Панель адміністратора",
        'product_catalog_button': "🛍️ Каталог товарів",
        'my_profile_button': "👤 Мій профіль",
        'my_orders_button': "📋 Мої замовлення",
        'help_button': "ℹ️ Допомога",
        'missing_name': "👤 Ім'я",
        'missing_email': "📧 Email",
        'missing_address_ukraine': "📍 Доставка (Місто/Відділення)",
        'missing_address_international': "📍 Доставка (Місто/Індекс)",
        'missing_phone': "📞 Телефон",
        'admin_welcome': "👑 **Панель адміністратора**\n\nЗ поверненням, **{safe_name}**! ⚡️\nВсе під контролем. Який план на сьогодні?\n\n👇 **Центр керування:**",
        'main_menu_button': "🔙 Головне меню",
        'catalog_empty': "📂 <b>Каталог порожній!</b>",
        'product_catalog': "📂 <b>Каталог товарів</b>",
        'page_indicator': " (Сторінка {page}/{total_pages})",
        'select_category': "\n\nВиберіть категорію 👇",
        'prev_button': "⬅️ Назад",
        'next_button': "Вперед ➡️",
        'in_stock': "✅ <b>В наявності</b>",
        'low_stock': "⚠️ <b>Мало товару</b> ({stock})",
        'out_of_stock': "❌ <b>Немає в наявності</b>",
        'variant_display': "\n🔹 <b>{v_type}:</b> {', '.join(map(str, opt_list))}",
        'price_from': "від {price}{currency_symbol}",
        'no_description': "Немає опису.",
        'product_details': "💰 Ціна: <b>{display_price}</b>\n📦 Статус: {stock_status}\n🛒 В кошику: <b>{in_cart}</b>",
        'minus_button': "➖",
        'plus_button': "➕",
        'cart_button_count': "🛒 Кошик ({in_cart})",
        'cart_button': "🛒 Кошик",
        'back_button': "🔙 Назад",
        'error': "❌ Помилка",
        'color_variant_key': "color",
        'colour_variant_key': "colour",
        'color_variant_key_uk': "колір",
        'color_variant_key_ru': "цвєт",
        'size_variant_key': "size",
        'size_variant_key_uk': "розмір",
        'size_variant_key_ru': "размер",
        'not_set': "Не вказано",
        'shipping_label_profile_ukraine': "Доставка (Місто/Відділення):",
        'shipping_label_profile_international': "Доставка (Місто/Індекс):",
        'profile_details': "👤 <b>Мій профіль</b>\n\n<b>Ім'я:</b> {name}\n\n<b>Email:</b> {email}\n\n<b>{shipping_label}</b>\n{address}\n\n<b>Телефон:</b> {phone}",
        'edit_name_button': "✏️ Редагувати ім'я",
        'edit_email_button': "✏️ Редагувати Email",
        'edit_shipping_info_button': "✏️ Редагувати інформацію про доставку",
        'edit_phone_button': "✏️ Редагувати телефон",
        'delete_data_button': "🗑️ Видалити дані",
        'invalid_action': "Неправильна дія",
        'data_deleted': "✅ {display_name} видалено!",
        'cancel_button': "❌ Скасувати",
        'enter_full_name': "👤 <b>Введіть ваше повне ім'я:</b>\n\n<b>Приклад:</b> <i>Іван Іванов</i>",
        'enter_email': "📧 <b>Введіть ваш email:</b>\n\n<b>Приклад:</b> <i>user@example.com</i>",
        'enter_address_ukraine': "📍 <b>Введіть місто, службу доставки та номер відділення:</b>\n\n<b>Приклад:</b> <i>Київ, Нова Пошта #15</i>",
        'enter_address_international': "📍 <b>Введіть повну адресу:</b>\n\n<b>Формат:</b> Країна, Місто, Вулиця/Будинок, Індекс\n\n<b>Приклад:</b> <i>Німеччина, Берлін, Гауптштрассе 10, 10115</i>",
        'enter_phone': "📞 <b>Введіть ваш номер телефону:</b>\n\n<b>Приклад:</b> <i>{example}</i>",
        'go_to_catalog_button': "📂 Перейти до каталогу",
        'my_orders_button_2': "📜 Мої замовлення",
        'cart_header': "🛒 <b>Ваш кошик:</b>\n\n",
        'cart_total': "\n💰 <b>Всього: {total_amount}{currency_symbol}</b>",
        'checkout_button': "✅ Оформити замовлення",
        'clear_cart_button': "🗑 Очистити кошик",
        'back_to_catalog_button': "📂 Повернутися до каталогу",
        'product_not_found': "❌ Товар не знайдено",
        'add_one_more_button': "🛒 Додати ще один",
        'back_to_cart_button': "🔙 Повернутися до кошика",
        'image_unavailable': "⚠️ (Зображення недоступне)",
        'stock_limit': "❌ В наявності залишилося лише {limit} одиниць!",
        'cart_empty_2': "Кошик порожній",
        'session_expired': "❌ Сесія застаріла",
        'select_variant': "👇 Виберіть **{current_key}**:",
        'limit_reached': "❌ Ліміт досягнуто! Доступно лише {limit}.",
        'added_to_cart': "✅ Додано до кошика!",
        'removed_from_cart': "➖ Видалено з кошика",
        'maximum_amount_reached': "❌ Досягнуто максимальної кількості",
        'added_amount': "➕ {product_name}. Кількість: {current_qty}",
        'removed_amount': "➖ {product_name}. Кількість: {current_qty}",
        'product_removed_from_cart': "🗑️ {product_name} видалено з кошика!",
        'cart_cleared': "🗑️ Кошик очищено! {items_count} товарів видалено",
        'in_stock_2': "📦 **В наявності:** {stock}",
        'out_of_stock_2': "❌ **НЕМАЄ В НАЯВНОСТІ**",
        'add_button': "➕ Додати",
        'remove_button': "➖ Видалити",
        'go_to_cart_button_count': "🛒 Перейти до кошика ({cart_qty})",
        'back_to_category_button': "🔙 Повернутися до {product_category}",
        'cart_empty_3': "Ваш кошик порожній",
        'use_profile_data_button': "👤 Використовувати мої дані профілю",
        'cancel_order_button': "❌ Скасувати замовлення",
        'checkout_step_1': "📋 <b>Крок 1/4: Повне ім'я</b>\n\nБудь ласка, введіть повне ім'я отримувача:\n\n<b>Приклад:</b> <i>Іван Іванов</i>",
        'loading_profile_data': "Завантаження даних профілю...",
        'checkout_profile_loaded_header': "📋 <b>Оформлення замовлення</b> (Дані профілю завантажено)\n\n",
        'checkout_header': "📋 <b>Оформлення замовлення</b>\n\n",
        'checkout_step_1_of_4': "👤 <b>Крок 1/{total_steps}: Повне ім'я</b>\n\nБудь ласка, введіть повне ім'я отримувача:\n\n<b>Приклад:</b> <i>Іван Іванов</i>",
        'checkout_step_2_of_4': "📧 <b>Крок 2/{total_steps}: Адреса електронної пошти</b>\n\nБудь ласка, введіть ваш email:\n\n<b>Приклад:</b> <i>user@gmail.com</i>",
        'checkout_step_3_of_4_ukraine': "📍 <b>Крок 3/{total_steps}: Інформація про доставку</b>\n\nВведіть місто та відділення Нової Пошти:\n\n<b>Приклад:</b> <i>Київ, Нова Пошта #15</i>",
        'checkout_step_3_of_4_international': "📍 <b>Крок 3/{total_steps}: Інформація про доставку</b>\n\nВведіть повну адресу (Країна, Місто, Вулиця, Індекс):\n\n<b>Приклад:</b> <i>Німеччина, Берлін, Гауптштрассе 10, 10115</i>",
        'checkout_step_4_of_4': "📱 <b>Крок 4/{total_steps}: Номер телефону</b>\n\nВведіть номер телефону з кодом країни:\n\n<b>Приклад:</b> <i>{example}</i>",
        'back_button_2': "🔙 Назад",
        'order_cancelled_2': "❌ Замовлення скасовано.",
        'confirm_details': "🔍 <b>Підтвердьте ваші дані:</b>\n\n👤 <b>Ім'я:</b> {full_name}\n📧 <b>Email:</b> {email}\n📍 <b>Доставка:</b> {address}\n📱 <b>Телефон:</b> {phone}\n\n<code>────────────────────</code>\nНатисніть <b>✏️ Редагувати</b> біля поля, щоб змінити його, або ✅, щоб продовжити.",
        'edit_name_button_2': "✏️ Редагувати ім'я",
        'edit_email_button_2': "✏️ Редагувати Email",
        'edit_shipping_button': "✏️ Редагувати доставку",
        'edit_phone_button_2': "✏️ Редагувати телефон",
        'everything_is_correct_button': "✅ Все вірно",
        'no_products_yet': "Тут ще немає товарів!",
        'category_header': "📂 <b>{category}</b>\nСторінка {prod_page}/{total_pages}",
        'back_to_catalog_button_2': "🔙 Повернутися до каталогу",
        'unknown': "Невідомо",
        'new_order_notification_ukraine': "🇺🇦 НОВЕ ЗАМОВЛЕННЯ",
        'delivery_notification_ukraine': "📍 Доставка:",
        'payment_notification_ukraine': "💳 Оплата:",
        'new_order_notification_international': "🌎 NEW ORDER",
        'delivery_notification_international': "📍 Shipping:",
        'payment_notification_international': "💳 Payment:",
        'admin_new_order_notification': "🔔 <b>{region_header} #{order_id}</b>\n\n👤 <b>Клієнт:</b> {full_name}\n📧 <b>Email:</b> {email}\n📞 <b>Телефон:</b> {phone}\n<b>{address_label}</b> {address}\n\n{pay_label} {payment_method}\n\n📦 <b>Товари:</b>\n{items_str}\n\n💰 <b>Загальна сума: {total_amount}{currency_symbol}</b>",
        'failed_to_notify_admin': "Не вдалося сповістити адміністратора {admin}: {e}",
        'order_failed_cart_empty': "⚠️ Помилка: Замовлення не вдалося. Можливо, кошик порожній.",
        'no_orders_yet': "🛒 <b>У вас ще немає замовлень.</b>",
        'your_orders_header': "📋 <b>Ваші замовлення</b> (Сторінка {page}/{total_pages}):\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n\n",
        'status_pending': "🟡 Обробка",
        'status_confirmed': "🔵 Підтверджено",
        'status_shipped': "🟠 Відправлено",
        'status_delivered': "🟢 Доставлено",
        'status_cancelled': "🔴 Скасовано",
        'order_items': "📦 Товари в замовленні",
        'order_summary_line': "📋 <b>Замовлення #{order_id}</b>\n   {products_str}\n💰 <b>{total_amount}{currency_symbol}</b> | {status_text}\n🗓 {date}\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n\n",
        'details_button': "📄 Деталі #{order_id}",
        'order_not_found': "❌ Замовлення не знайдено",
        'items_info_unavailable': "📦 Інформація про товари недоступна\n",
        'order_details_text': "📋 <b>Замовлення #{order_id}</b>\n\n👤 <b>Клієнт:</b> {user_name}\n📧 <b>Email:</b> {email}\n📞 <b>Телефон:</b> {phone}\n📍 <b>Адреса:</b> {address}\n💳 <b>Оплата:</b> {payment_method}\n\n📦 <b>Товари:</b>\n{products_text}\n💰 <b>Всього: {total_amount}{currency_symbol}</b>\n\n📊 <b>Статус:</b> {status_display}\n🕐 <b>Дата:</b> {date}",
        'confirm_button': "🔵 Підтвердити",
        'sent_button': "🟠 Відправлено",
        'delivered_button': "🟢 Доставлено",
        'cancel_button_2': "🔴 Скасувати",
        'back_to_all_orders_button': "🔙 Повернутися до всіх замовлень",
        'cancel_order_button_3': "❌ Скасувати замовлення",
        'back_to_list_button': "🔙 Повернутися до списку",
        'access_denied': "❌ Доступ заборонено",
        'admin_panel_header': "👑 **ПАНЕЛЬ АДМІНІСТРАТОРА**\n\n👇 **Панель приладів:**",
        'all_orders_button': "📋 ВСІ ЗАМОВЛЕННЯ",
        'products_button': "📦 Товари",
        'stats_button': "📊 Статистика",
        'revenue_button': "📈 Дохід",
        'users_button': "👥 Користувачі",
        'main_menu_button_3': "🔙 Головне меню",
        'admin_stats_text': "👑 <b>СТАТИСТИКА АДМІНІСТРАТОРА</b>\n\n💰 <b>Загальний дохід:</b> {total_revenue}{currency_symbol}\n📦 <b>Всього замовлень:</b> {total_orders} (🟡 {pending_orders} нових)\n👥 <b>Користувачі:</b> {total_users} ({active_buyers} активних покупців)\n\n🏆 <b>Топ-5 бестселерів:</b>\n{top_text}\n\n📉 <b>Топ-5 найгірших продажів:</b>\n{bottom_text}\n\n<i>*Статистика на основі підтверджених/доставлених замовлень</i>",
        'no_data': 'Немає даних',
        'back_to_admin_panel_button': "🔙 Повернутися до панелі адміністратора",
        'product_management_header': "🛠 **Керування товарами**",
        'page_indicator_2': " (Сторінка {page}/{total_pages})",
        'select_category_to_edit': "\nВиберіть категорію для редагування товарів:",
        'category_button_count': "📂 {cat_name} ({count})",
        'add_product_button': "➕ Додати товар",
        'error_parsing_category': "Помилка розбору категорії",
        'category_header_2': "📂 Категорія: **{category}**\nСторінка {page}/{total_pages}\n\nВиберіть товар для редагування:",
        'back_to_categories_button': "🔙 Повернутися до категорій",
        'unblock_button': "✅ Розблокувати",
        'block_button': "⛔ Заблокувати",
        'user_id': "ID: {user_id}",
        'user_display': "👤 {user_display}",
        'admin_panel_button_2': "🔙 Панель адміністратора",
        'user_management_header': "👥 **Керування користувачами**\nСторінка {page} з {total_pages}\nВсього користувачів: {total_users}",
        'all_time': "за весь час",
        'today': "сьогодні",
        'last_7_days': "за останні 7 днів",
        'last_30_days': "за останні 30 днів",
        'financial_report': "💰 <b>ФІНАНСОВИЙ ЗВІТ</b> ({label})\n\n💵 <b>Загальний дохід:</b> {total_rev}{currency_symbol}\n💳 <b>Середній чек:</b> {avg_check}{currency_symbol}\n📦 <b>Кількість продажів:</b> {total_orders}\n\n⏳ <b>Дохід в очікуванні:</b> {pending_rev}{currency_symbol}\n<i>*Враховуються лише підтверджені/доставлені замовлення</i>",
        'today_button': "📅 Сьогодні",
        'week_button': "📅 Тиждень",
        'month_button': "📅 Місяць",
        'all_time_button': "📊 За весь час",
        'access_denied_not_admin': "Доступ заборонено: ви не адміністратор.",
        'no_orders_in_db': "В базі даних не знайдено замовлень.",
        'all_orders_header': "<b>📦 Всі замовлення (Сторінка {page}/{total_pages}):</b>\n\n",
        'details_button_2': "Деталі #{order_id}",
        'back_to_admin_button': "🔙 Повернутися до адмін-панелі",
        'error_parsing_data': "❌ Помилка розбору даних",
        'status_updated': "✅ Статус оновлено: {new_status}",
        'order_update_notification_ukraine': "📦 <b>Замовлення #{order_id} оновлено</b>\n\n🆕 Новий статус: <b>{display_status}</b>\n\nДякуємо за покупку! ❤️",
        'order_update_notification_international': "📦 <b>Order #{order_id} update</b>\n\n🆕 New status: <b>{display_status}</b>\n\nThank you for shopping with us! ❤️",
        'failed_to_notify_user': "⚠️ Не вдалося сповістити користувача: {e}",
        'product_management_header_2': "📦 **Керування товарами:**\n\n",
        'edit_button': "✏️",
        'delete_button': "🗑️",
        'add_product_button_2': "➕ Додати товар",
        'admin_panel_button_3': "🔙 Панель адміністратора",
        'admin_variant_type_prompt': "Вибрано: <b>{variant_type}</b>\n\n⌨️ Введіть доступні опції через кому.\n\n<b>Формати:</b>\n1. <code>Опція=Кількість</code> (Ціна за замовчуванням)\n2. <code>Опція=Кількість=Ціна</code> (Власна ціна)\n\n✅ <b>Приклад для {variant_type}:</b>\n<code>{example_text}</code>",
        'order_not_found_2': "Замовлення не знайдено",
        'order_already_status': "Замовлення вже має статус {current_status}",
        'order_accepted': "✅ Замовлення #{order_id} ПРИЙНЯТО!",
        'your_order_accepted': "✅ Ваше замовлення #{order_id} було прийнято!",
        'order_rejected': "❌ Замовлення #{order_id} ВІДХИЛЕНО. Сток відновлено.",
        'your_order_canceled': "❌ Ваше замовлення #{order_id} було скасовано.",
        'error_restoring_stock': "Помилка відновлення стоку",
        'product_management_details': "🛠 **Керування товарами**\n\n📌 ID: `{product_id}`\n📦 Загальний сток: {stock}\n{stock_details}\n📝 Назва: {name}\n📄 Опис: {description}\n💰 Ціна: {display_price}\n📂 Категорія: {category}\n😀 Емодзі: {emoji}\n\nВиберіть дію:",
        'edit_name_button_3': "✏️ Назва",
        'edit_desc_button': "✏️ Опис",
        'edit_price_button': "✏️ Ціна",
        'edit_stock_button': "✏️ Сток",
        'edit_category_button': "✏️ Категорія",
        'edit_emoji_button': "✏️ Емодзі",
        'edit_image_button': "✏️ Зображення",
        'edit_variants_button': "✏️ Варіанти",
        'delete_product_button': "🗑️ Видалити товар",
        'back_to_list_button_2': "🔙 Повернутися до списку",
        'invalid_request_2': "❌ Неправильний запит",
        'product_not_found_2': "❌ Товар не знайдено",
        'none': "❌ Немає",
        'edit_button_2': "✏️ Редагувати",
        'delete_button_2': "🗑️ Видалити",
        'to_products_button': "🔙 До товарів",
        'adding_new_product_name': "📦 **Додавання нового товару**\n\nВведіть назву товару:",
        'set': "✅ Встановлено",
        'not_set_2': "❌ не встановлено",
        'edit_product_details': "✏️ **Редагувати товар**\n\n{emoji} **{name}**\nОпис: {description}\nЦіна: {price}{currency_symbol}\nКатегорія: {category}\nСток: {stock}\nЗображення: {has_img}\nВаріанти: {has_vars}",
        'name': "Назва",
        'desc': "Опис",
        'price': "Ціна",
        'category': "Категорія",
        'emoji': "Емодзі",
        'stock': "Сток",
        'variants': "Варіанти",
        'image': "Зображення",
        'back_to_products_button': "🔙 Повернутися до товарів",
        'enter_new_name': "✏️ Введіть нову назву:",
        'enter_new_description': "📝 Введіть новий опис:",
        'enter_new_price': "💰 Введіть нову ціну (число):",
        'enter_new_category': "📂 Введіть нову категорію:",
        'enter_new_emoji': "😀 Введіть новий емодзі:",
        'enter_new_stock': "📦 Введіть новий сток (ціле число):",
        'editing_variants': "🎨 **Редагування варіантів**",
        'editing_variants_instructions': "🎨 **Редагування варіантів**\n\n👇 **Поточні налаштування:**\n{current_text}\n\n✍️ **Щоб ЗМІНИТИ, надішліть список:**\n`Тип: Опція=К-сть` або `Тип: Опція=К-сть=Ціна`\n\nПриклад: `Колір: Червоний=10, Синій=5=900`\n🗑️ Надішліть `-`, щоб видалити всі варіанти.",
        'product_image_management': "🖼️ **Керування зображенням товару**\n\nТовар: **{product_name}**\nСтатус: {status}",
        'add_photo_button': "➕ Додати фото",
        'change_photo_button': "✏️ Змінити фото",
        'delete_photo_button': "🗑️ Видалити фото",
        'back_to_editing_button': "🔙 Повернутися до редагування",
        'cancel_button_3': "🔙 Скасувати",
        'send_product_image': "📸 **Надішліть зображення товару** (або URL-посилання):",
        'image_deleted': "🗑️ Зображення видалено!",
        'product_image_management_no_image': "🖼️ **Керування зображенням товару**\n\nСтатус: ❌ Немає зображення",
        'confirm_delete_product': "🗑️ Ви впевнені, що хочете видалити **{name}**?",
        'yes_delete_button': "❌ Так, видалити",
        'cancelled': "🚫 Скасовано",
        'product_already_deleted': "❌ Товар вже видалено",
        'product_deleted': "🗑️ {name} видалено!",
        'use_start': "Використовуйте /start для навігації по магазину! 🛍️",
        'enter_product_description': "📝 <b>Введіть опис товару:</b>",
        'simple_product_button': "📦 Простий товар",
        'has_variants_button': "🎨 Має варіанти",
        'choose_product_type': "❓ <b>Виберіть тип товару:</b>",
        'enter_stock': "🔢 <b>Введіть кількість:</b>",
        'invalid_price': "⚠️ <b>Неправильна ціна!</b>",
        'enter_category': "📂 <b>Введіть категорію:</b>",
        'invalid_quantity': "⚠️ <b>Неправильна кількість!</b>",
        'enter_emoji': "✨ <b>Введіть емодзі:</b>",
        'send_photo': "📸 <b>Надішліть фото:</b>",
        'product_created': "✅ Товар <b>{name}</b> створено!",
        'back_button_3': "🔙 Назад",
        'status_message': "✨ <b>{status_msg}</b>\n\n",
        'select_variant_type': "🎨 <b>Виберіть тип варіанту:</b>\n\n{added_info}Виберіть категорію або натисніть <b>Готово</b>.",
        'error_handler': "❌ Сталася помилка. Будь ласка, спробуйте ще раз або використайте /start",
        'add_variants_before_finishing': "⚠️ Додайте варіанти перед завершенням!",
        'product_created_2': "✅ <b>{name}</b> створено!",
        'welcome_promo_1': "Залишився всього 1 крок до завершення профілю! ✨",
        'welcome_promo_2': "Майже готово! Заповніть ще 2 поля для швидкого замовлення. 🚀",
        'welcome_promo_3': "Ваш профіль заповнений лише частково. Додайте дані для зручності. 📦",
        'welcome_promo_4': "Вітаємо! Заповніть свій профіль, щоб оформляти замовлення в один клік. 👇",
        'missing_fields_info': "\n{promo}\n⚠️ <b>Заповніть ці дані:</b> {missing_labels}\n────────────────────",
        'invoice_title': "Оплата замовлення — {shop_name}",
        'invoice_desc': "Оплата товарів у вашому кошику",
        'invoice_label': "Загальна сума",
        'stock_out_error': "Вибачте, {name} вже закінчився!",
        'method_online_card': "Онлайн оплата картою",
        'method_card_courier': "Картою кур'єру",
        'method_cod': "Готівка (накладений платіж)",
        'admin_wizard_simple_price': "💰 <b>Крок 3: Ціна</b>\n\nВведіть ціну товару (тільки число).\n<b>Приклад:</b> <code>1250</code> або <code>45.50</code>",
        'admin_wizard_simple_stock': "🔢 <b>Крок 4: Кількість</b>\n\nВведіть кількість товару на складі.\n<b>Приклад:</b> <code>100</code>",
        'admin_wizard_variant_photo': "🎨 <b>Крок 3: Фото</b>\n\nНадішліть фото товару або пряме посилання на нього.\nЯкщо фото не потрібне, надішліть символ <code>-</code>",
        'error_photo_required': "⚠️ <b>Помилка: Потрібно фото!</b>\n\nБудь ласка, завантажте файл зображення або надішліть пряме посилання (http...).\nЯкщо фото не потрібне, введіть <code>-</code>",
        'variant_format_hint': "✍️ <b>Введіть варіанти у форматі:</b>\n<code>Опція=Кількість=Ціна</code>\n\n<b>Приклад:</b> <code>XL=10=1500, L=5=1400</code>",
        'admin_bank_details': "Будь ласка, використайте наступні реквізити для оплати:\n\n<b>Отримувач:</b> {recipient}\n<b>IBAN:</b> <code>{iban}</code>\n<b>Призначення:</b> {purpose}\n\n────────────────────\nБудь ласка, надішліть скріншот підтвердження нашій підтримці після оплати.",
        'admin_img_status_set': "✅ Зображення встановлено",
        'admin_img_status_none': "❌ Немає зображення",
        'admin_product_created_simple': "✅ Товар створено!",
        'admin_category_updated': "✅ Категорію оновлено на **{category}**!",
        'admin_stock_details_header': "\n📊 <b>Деталі складу:</b>\n",
        'variant_default_format': "Опція=К-сть=Ціна",
        'variant_error_title': "⚠️ <b>Помилка формату для {v_type}!</b>",
        'variant_error_msg': "Будь ласка, використовуйте: <code>Опція=К-сть=Ціна</code>",
        'variant_example_label': "<b>Приклад:</b>",
        'admin_ex_Size': "S=10=1200, M=5=1300, L=2=1400",
        'admin_ex_Color': "Червоний=10=500, Синій=5=550",
        'admin_ex_Memory': "128GB=10=800, 256GB=5=950",
        'admin_ex_Volume': "0.5L=10=50, 1L=20=90",
        'admin_ex_Weight': "1kg=10=100, 5kg=2=450",
        'admin_ex_ShoeSize': "41=5=2500, 42=10=2500",
        'admin_ex_default': "Опція=К-сть=Ціна",
        'variant_input_prompt': "📥 <b>Введіть опції для {v_type}:</b>\n\n<b>Формат:</b> <code>Опція=К-сть=Ціна</code>\n<b>Приклад:</b> <code>{example}</code>",
        'back_to_types_btn': "🔙 Назад до типів",

        'admin_wizard_variant_title': "🎨 <b>Керування варіантами</b>\n\n{added_info}Оберіть тип варіанту для додавання або натисніть <b>Готово</b>:",
        'active_variant_label': "📍 <b>Активно:</b> ",
        'type_Size': "Розмір",
        'type_Color': "Колір",
        'type_Memory': "Пам'ять",
        'type_Volume': "Об'єм",
        'type_Weight': "Вага",
        'type_ShoeSize': "Розмір взуття",

        # Summary screen
        'summary_title': "🔍 Перевірте ваші дані",
        'summary_confirm_btn': "✅ Все вірно",
        'summary_edit_name_btn': "✏️ Ім'я",
        'summary_edit_email_btn': "✏️ Email",
        'summary_edit_address_btn': "✏️ Доставка",
        'summary_edit_phone_btn': "✏️ Телефон",
        'summary_name_label': "👤 Ім'я",
        'summary_email_label': "📧 Email",
        'summary_address_label': "📍 Доставка",
        'summary_phone_label': "📱 Телефон",

        # Profile/Checkout validation errors
        'err_invalid_name': "❌ <b>Некоректне ім'я</b>\n\n<b>Приклад:</b> <i>Іван Іванов</i>\n\nБудь ласка, спробуйте ще раз:",
        'err_invalid_email': "❌ <b>Некоректний формат email</b>\n\n<b>Приклад:</b> <i>user@example.com</i>\n\nБудь ласка, спробуйте ще раз:",
        'err_invalid_phone': "❌ <b>Некоректний номер телефону</b>\n\n<b>Приклад:</b> <i>+380501234567</i>\n\nБудь ласка, спробуйте ще раз:",
        'err_invalid_address': "❌ <b>Адреса надто коротка</b>\n\n<b>Приклад:</b> <i>Київ, Нова Пошта #15</i>\n\nБудь ласка, спробуйте ще раз:",

        # Edit field screen (checkout)
        'edit_field_title': "✏️ Редагування: {field}",
        'current_value_label': "Поточне значення:",
        'example_label': "Приклад:",
        'back_to_summary_btn': "🔙 Повернутись до перевірки",
        'enter_new_value_prompt': "Будь ласка, введіть нове значення нижче:",
    },




    'INTERNATIONAL': {
        'column_added': "✅ Column '{column_name}' added to table '{table_name}'!",
        'error_adding_column': "⚠️ Error adding column {column_name} to {table_name}: {e}",
        'shipping_label_ukraine': "📍 Shipping (City/Branch):",
        'shipping_label_international': "📍 Shipping:",
        'receipt': (
            "✅ {bold_start}Order #{order_id} has been successfully placed!{bold_end}\n\n"
            "👤 {bold_start}Customer:{bold_end} {user_name}\n\n"
            "📧 {bold_start}Email:{bold_end} {email}\n\n"
            "📞 {bold_start}Phone:{bold_end} {phone}\n\n"
            "{bold_start}{shipping_label}{bold_end}\n{address}\n\n"
            "💳 {bold_start}Payment Method:{bold_end} {payment}\n\n"
            "📦 {bold_start}Products:{bold_end}\n{products_text}\n"
            "💰 {bold_start}Total Amount: {total}{currency_symbol}{bold_end}\n\n"
            "📋 {bold_start}Status:{bold_end} In progress\n\n"
            "🕐 {bold_start}Date:{bold_end} {date}\n\n"
            "Thank you for shopping with us! 🛍️"
        ),
        'product': "Product",
        'price_calculation_error': "Error calculating price: {e}",
        'size_variant': "📏 Size (S, M, L)",
        'color_variant': "🎨 Color",
        'memory_variant': "💾 Memory (GB)",
        'volume_variant': "🥛 Volume (L, ml)",
        'weight_variant': "⚖️ Weight (kg, g)",
        'shoe_size_variant': "👟 Shoe Size",
        'finish_skip_variant': "✅ Finish / Skip",
        'user_blocked': "You are blocked from using this bot.",
        'user_blocked_inline': "You are blocked from using this bot.",
        'invalid_request': "❌ Invalid request",
        'order_already_delivered_or_canceled': "❌ Order has already been delivered or canceled",
        'customer_canceled_order': "🔴 The customer canceled the order. #{order_id}",
        'order_canceled': "✅ Order canceled",
        'my_cart_count': "🛒 My cart ({cart_count})",
        'my_cart': "🛒 My cart",
        'admin_panel_button': "👑 <b>Admin Panel</b>",
        'product_catalog_button': "🛍️ Product catalog",
        'my_profile_button': "👤 My profile",
        'my_orders_button': "📋 My orders",
        'help_button': "ℹ️ Help",
        'missing_name': "👤 Name",
        'missing_email': "📧 Email",
        'missing_address_ukraine': "📍 Shipping (City/Branch)",
        'missing_address_international': "📍 Shipping (City/ZIP)",
        'missing_phone': "📞 Phone",
        'admin_welcome': "👑 <b>Welcome back, {safe_name}</b>! \n\n⚡️ Everything is under control. What's the plan for today?\n\n👇 <b>Control Center:</b>",
        'main_menu_button': "🔙 Main menu",
        'catalog_empty': "📂 <b>Catalog is empty!</b>",
        'product_catalog': "📂 <b>Product Catalog</b>",
        'page_indicator': " (Page {page}/{total_pages})",
        'select_category': "\n\nSelect a category 👇",
        'prev_button': "⬅️ Prev",
        'next_button': "Next ➡️",
        'in_stock': "✅ <b>In Stock</b>",
        'low_stock': "⚠️ <b>Low Stock</b> ({stock})",
        'out_of_stock': "❌ <b>Out of Stock</b>",
        'variant_display': "\n🔹 <b>{v_type}:</b> {', '.join(map(str, opt_list))}",
        'price_from': "from {price}{currency_symbol}",
        'no_description': "No description.",
        'product_details': "💰 Price: <b>{display_price}</b>\n📦 Status: {stock_status}\n🛒 In Cart: <b>{in_cart}</b>",
        'minus_button': "➖",
        'plus_button': "➕",
        'cart_button_count': "🛒 Cart ({in_cart})",
        'cart_button': "🛒 Cart",
        'back_button': "🔙 Back",
        'error': "❌ Error",
        'color_variant_key': "color",
        'colour_variant_key': "colour",
        'color_variant_key_uk': "колір",
        'color_variant_key_ru': "цвєт",
        'size_variant_key': "size",
        'size_variant_key_uk': "розмір",
        'size_variant_key_ru': "размер",
        'not_set': "Not set",
        'shipping_label_profile_ukraine': "Shipping (City/Branch):",
        'shipping_label_profile_international': "Shipping (City/ZIP):",
        'profile_details': "👤 <b>My Profile</b>\n\n<b>Name:</b> {name}\n\n<b>Email:</b> {email}\n\n<b>{shipping_label}</b>\n{address}\n\n<b>Phone:</b> {phone}",
        'edit_name_button': "✏️ Edit Name",
        'edit_email_button': "✏️ Edit Email",
        'edit_shipping_info_button': "✏️ Edit Shipping Info",
        'edit_phone_button': "✏️ Edit Phone",
        'delete_data_button': "🗑️ Delete Data",
        'invalid_action': "Invalid action",
        'data_deleted': "✅ {display_name} deleted!",
        'cancel_button': "❌ Cancel",
        'enter_full_name': "👤 <b>Enter your Full Name:</b>\n\n<b>Example:</b> <i>John Doe</i>",
        'enter_email': "📧 <b>Enter your email:</b>\n\n<b>Example:</b> <i>user@example.com</i>",
        'enter_address_ukraine': "📍 <b>Enter City, Delivery Service, and Branch #:</b>\n\n<b>Example:</b> <i>Kyiv, Nova Poshta #15</i>",
        'enter_address_international': "📍 <b>Enter Full Address:</b>\n\n<b>Format:</b> Country, City, Street/House, ZIP\n\n<b>Example:</b> <i>Germany, Berlin, Hauptstraße 10, 10115</i>",
        'enter_phone': "📞 <b>Enter your phone number:</b>\n\n<b>Example:</b> <i>{example}</i>",
        'cart_empty': "🛒 **Your cart is empty!**\n\nLooks like you haven't added anything yet.\nCheck out our catalog to find something cool! 👇",
        'go_to_catalog_button': "📂 Go to Catalog",
        'my_orders_button_2': "📜 My Orders",
        'cart_header': "🛒 **Your Cart:**\n\n",
        'cart_total': "\n💰 **Total: {total_amount}{currency_symbol}**",
        'checkout_button': "✅ Checkout",
        'clear_cart_button': "🗑 Clear Cart",
        'back_to_catalog_button': "📂 Back to Catalog",
        'product_not_found': "❌ Product not found",
        'add_one_more_button': "🛒 Add One More",
        'back_to_cart_button': "🔙 Back to Cart",
        'image_unavailable': "⚠️ (Image unavailable)",
        'stock_limit': "❌ Only {max_stock} items left in stock!",
        'cart_empty_2': "Cart empty",
        'session_expired': "❌ Session expired",
        'select_variant': "👇 Select **{current_key}**:",
        'limit_reached': "❌ Stock limit reached! Only {limit} items available.",
        'added_to_cart': "✅ Added to cart!",
        'removed_from_cart': "➖ Removed from cart",
        'maximum_amount_reached': "❌ Maximum amount reached",
        'added_amount': "➕ {product_name}. Amount: {current_qty}",
        'removed_amount': "➖ {product_name}. Amount: {current_qty}",
        'product_removed_from_cart': "🗑️ {product_name} removed from cart!",
        'cart_cleared': "🗑️ Cart cleared! {items_count} items removed",
        'in_stock_2': "📦 **In Stock:** {stock}",
        'out_of_stock_2': "❌ **OUT OF STOCK**",
        'add_button': "➕ Add",
        'remove_button': "➖ Remove",
        'go_to_cart_button_count': "🛒 Go to Cart ({cart_qty})",
        'back_to_category_button': "🔙 Back to {product_category}",
        'cart_empty_3': "Your cart is empty",
        'use_profile_data_button': "👤 Use my Profile Data",
        'cancel_order_button': "❌ Cancel Order",
        'checkout_step_1': "📋 <b>Step 1/4: Full Name</b>\n\nPlease enter the recipient's full name:\n\n<b>Example:</b> <i>John Doe</i>",
        'loading_profile_data': "Loading profile data...",
        'checkout_profile_loaded_header': "📋 <b>Checkout</b> (Profile data loaded)\n\n",
        'checkout_header': "📋 <b>Order Checkout</b>\n\n",
        'checkout_step_1_of_4': "👤 <b>Step 1/{total_steps}: Full Name</b>\n\nPlease enter the recipient's full name:\n\n<b>Example:</b> <i>John Doe</i>",
        'checkout_step_2_of_4': "📧 <b>Step 2/{total_steps}: Email Address</b>\n\nPlease enter your email:\n\n<b>Example:</b> <i>user@gmail.com</i>",
        'checkout_step_3_of_4_ukraine': "📍 <b>Step 3/{total_steps}: Shipping Info</b>\n\nEnter City and Nova Poshta Branch:\n\n<b>Example:</b> <i>Kyiv, Nova Poshta #15</i>",
        'checkout_step_3_of_4_international': "📍 <b>Step 3/{total_steps}: Shipping Info</b>\n\nEnter Full Address (Country, City, Street, ZIP):\n\n<b>Example:</b> <i>Germany, Berlin, Hauptstraße 10, 10115</i>",
        'checkout_step_4_of_4': "📱 <b>Step 4/{total_steps}: Phone Number</b>\n\nEnter phone with country code:\n\n<b>Example:</b> <i>{example}</i>",
        'back_button_2': "🔙 Back",
        'order_cancelled_2': "❌ Order cancelled.",
        'confirm_details': "🔍 <b>Confirm your details:</b>\n\n👤 <b>Name:</b> {full_name}\n📧 <b>Email:</b> {email}\n📍 <b>Shipping:</b> {address}\n📱 <b>Phone:</b> {phone}\n\n<code>────────────────────</code>\nClick <b>✏️ Edit</b> next to a field to change it, or ✅ to proceed.",
        'edit_name_button_2': "✏️ Edit Name",
        'edit_email_button_2': "✏️ Edit Email",
        'edit_shipping_button': "✏️ Edit Shipping",
        'edit_phone_button_2': "✏️ Edit Phone",
        'everything_is_correct_button': "✅ Everything is correct",
        'no_products_yet': "No products here yet!",
        'category_header': "📂 <b>{category}</b>\nPage {prod_page}/{total_pages}",
        'back_to_catalog_button_2': "🔙 Back to Catalog",
        'unknown': "Unknown",
        'new_order_notification_ukraine': "🇺🇦 NEW ORDER",
        'delivery_notification_ukraine': "📍 Shipping:",
        'payment_notification_ukraine': "💳 Payment:",
        'new_order_notification_international': "🌎 NEW ORDER",
        'delivery_notification_international': "📍 Shipping:",
        'payment_notification_international': "💳 Payment:",
        'admin_new_order_notification': "🔔 <b>{region_header} #{order_id}</b>\n\n👤 <b>Customer:</b> {full_name}\n📧 <b>Email:</b> {email}\n📞 <b>Phone:</b> {phone}\n<b>{address_label}</b> {address}\n\n{pay_label} {payment_method}\n\n📦 <b>Products:</b>\n{items_str}\n\n💰 <b>Total Amount: {total_amount}{currency_symbol}</b>",
        'failed_to_notify_admin': "Failed to notify admin {admin}: {e}",
        'order_failed_cart_empty': "⚠️ Error: Order failed. Cart might be empty.",
        'no_orders_yet': "🛒 <b>You have no orders yet.</b>",
        'your_orders_header': "📋 <b>Your orders</b> (Page {page}/{total_pages}):\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n\n",
        'status_pending': "🟡 Processing",
        'status_confirmed': "🔵 Confirmed",
        'status_shipped': "🟠 Sent",
        'status_delivered': "🟢 Delivered",
        'status_cancelled': "🔴 Cancelled",
        'order_items': "📦 Order Items",
        'order_summary_line': "📋 <b>Order #{order_id}</b>\n   {products_str}\n💰 <b>{total_amount}{currency_symbol}</b> | {status_text}\n🗓 {date}\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n\n",
        'details_button': "📄 Details #{order_id}",
        'order_not_found': "❌ Order not found",
        'items_info_unavailable': "📦 Items info unavailable\n",
        'order_details_text': "📋 <b>Order #{order_id}</b>\n\n👤 <b>Customer:</b> {user_name}\n📧 <b>Email:</b> {email}\n📞 <b>Phone:</b> {phone}\n📍 <b>Address:</b> {address}\n💳 <b>Payment:</b> {payment_method}\n\n📦 <b>Products:</b>\n{products_text}\n💰 <b>Total: {total_amount}{currency_symbol}</b>\n\n📊 <b>Status:</b> {status_display}\n🕐 <b>Date:</b> {date}",
        'confirm_button': "🔵 Confirm",
        'sent_button': "🟠 Sent",
        'delivered_button': "🟢 Delivered",
        'cancel_button_2': "🔴 Cancel",
        'back_to_all_orders_button': "🔙 Back to All Orders",
        'cancel_order_button_3': "❌ Cancel Order",
        'back_to_list_button': "🔙 Back to list",
        'access_denied': "❌ Access denied",
        'admin_panel_header': "👑 **ADMIN PANEL**\n\n👇 **Dashboard:**",
        'all_orders_button': "📋 ALL ORDERS",
        'products_button': "📦 Products",
        'stats_button': "📊 Stats",
        'revenue_button': "📈 Revenue",
        'users_button': "👥 Users",
        'main_menu_button_3': "🔙 Main menu",
        'admin_stats_text': "👑 <b>ADMIN STATISTICS</b>\n\n💰 <b>Total Revenue:</b> {total_revenue}{currency_symbol}\n📦 <b>Total Orders:</b> {total_orders} (🟡 {pending_orders} new)\n👥 <b>Users:</b> {total_users} ({active_buyers} active buyers)\n\n🏆 <b>Top 5 Best Sellers:</b>\n{top_text}\n\n📉 <b>Bottom 5 Sellers:</b>\n{bottom_text}\n\n<i>*Statistics based on confirmed/delivered orders</i>",
        'no_data': 'No data',
        'back_to_admin_panel_button': "🔙 Back to Admin Panel",
        'product_management_header': "🛠 **Product Management**",
        'page_indicator_2': " (Page {page}/{total_pages})",
        'select_category_to_edit': "\nSelect a category to edit items:",
        'category_button_count': "📂 {cat_name} ({count})",
        'add_product_button': "➕ Add Product",
        'error_parsing_category': "Error parsing category",
        'category_header_2': "📂 Category: **{category}**\nPage {page}/{total_pages}\n\nSelect a product to edit:",
        'back_to_categories_button': "🔙 Back to Categories",
        'unblock_button': "✅ Unblock",
        'block_button': "⛔ Block",
        'user_id': "ID: {user_id}",
        'user_display': "👤 {user_display}",
        'admin_panel_button_2': "🔙 Admin panel",
        'user_management_header': "👥 **User Management**\nPage {page} of {total_pages}\nTotal users: {total_users}",
        'all_time': "all time",
        'today': "today",
        'last_7_days': "last 7 days",
        'last_30_days': "last 30 days",
        'financial_report': "💰 <b>FINANCIAL REPORT</b> ({label})\n\n💵 <b>Total Revenue:</b> {total_rev}{currency_symbol}\n💳 <b>Average Check:</b> {avg_check}{currency_symbol}\n📦 <b>Sales Count:</b> {total_orders}\n\n⏳ <b>Pending Revenue:</b> {pending_rev}{currency_symbol}\n<i>*Only confirmed/delivered orders are included</i>",
        'today_button': "📅 Today",
        'week_button': "📅 Week",
        'month_button': "📅 Month",
        'all_time_button': "📊 All Time",
        'access_denied_not_admin': "Access denied: You are not an admin.",
        'no_orders_in_db': "No orders found in database.",
        'all_orders_header': "<b>📦 All Orders (Page {page}/{total_pages}):</b>\n\n",
        'details_button_2': "Details #{order_id}",
        'back_to_admin_button': "🔙 Back to Admin",
        'error_parsing_data': "❌ Error parsing data",
        'status_updated': "✅ Status updated: {new_status}",
        'order_update_notification_ukraine': "📦 <b>Order #{order_id} update</b>\n\n🆕 New status: <b>{display_status}</b>\n\nThank you for shopping with us! ❤️",
        'order_update_notification_international': "📦 <b>Order #{order_id} update</b>\n\n🆕 New status: <b>{display_status}</b>\n\nThank you for shopping with us! ❤️",
        'failed_to_notify_user': "⚠️ Failed to notify user: {e}",
        'product_management_header_2': "📦 **Product management:**\n\n",
        'edit_button': "✏️",
        'delete_button': "🗑️",
        'add_product_button_2': "➕ Add product",
        'admin_panel_button_3': "🔙 Admin panel",
        'order_not_found_2': "Order not found",
        'order_already_status': "Order is already {current_status}",
        'order_accepted': "✅ Order #{order_id} ACCEPTED!",
        'your_order_accepted': "✅ Your Order #{order_id} has been accepted!",
        'order_rejected': "❌ Order #{order_id} REJECTED. Stock restored.",
        'your_order_canceled': "❌ Your Order #{order_id} was canceled.",
        'error_restoring_stock': "Error restoring stock",
        'product_management_details': "🛠 **Product Management**\n\n📌 ID: `{product_id}`\n📦 Total Stock: {stock}\n{stock_details}\n📝 Name: {name}\n📄 Desc: {description}\n💰 Price: {display_price}\n📂 Category: {category}\n😀 Emoji: {emoji}\n\nSelect an action:",
        'edit_name_button_3': "✏️ Name",
        'edit_desc_button': "✏️ Desc",
        'edit_price_button': "✏️ Price",
        'edit_stock_button': "✏️ Stock",
        'edit_category_button': "✏️ Category",
        'edit_emoji_button': "✏️ Emoji",
        'edit_image_button': "✏️ Image",
        'edit_variants_button': "✏️ Variants",
        'delete_product_button': "🗑️ Delete Product",
        'back_to_list_button_2': "🔙 Back to List",
        'invalid_request_2': "❌ Invalid request",
        'product_not_found_2': "❌ Product not found",
        'none': "❌ None",
        'edit_button_2': "✏️ Edit",
        'delete_button_2': "🗑️ Delete",
        'to_products_button': "🔙 To products",
        'adding_new_product_name': "📦 **Adding a new product**\n\nEnter the name of the product:",
        'set': "✅ Set",
        'not_set_2': "❌ not set",
        'edit_product_details': "✏️ **Edit Product**\n\n{emoji} **{name}**\nDesc: {description}\nPrice: {price}{currency_symbol}\nCategory: {category}\nStock: {stock}\nImage: {has_img}\nVariants: {has_vars}",
        'name': "Name",
        'desc': "Desc",
        'price': "Price",
        'category': "Category",
        'emoji': "Emoji",
        'stock': "Stock",
        'variants': "Variants",
        'image': "Image",
        'back_to_products_button': "🔙 Back to Products",
        'enter_new_name': "✏️ Enter new name:",
        'enter_new_description': "📝 Enter new description:",
        'enter_new_price': "💰 Enter new price (number):",
        'enter_new_category': "📂 Enter new category:",
        'enter_new_emoji': "😀 Enter new emoji:",
        'enter_new_stock': "📦 Enter new stock (integer):",
        'editing_variants': "🎨 **Editing Variants**",
        'editing_variants_instructions': "🎨 **Editing Variants**\n\n👇 **Current settings:**\n{current_text}\n\n✍️ **To CHANGE, send a list:**\n`Type: Option=Qty` or `Type: Option=Qty=Price`\n\nExample: `Color: Red=10, Blue=5=900`\n🗑️ Send `-` to delete all variants.",
        'product_image_management': "🖼️ **Product Image Management**\n\nProduct: **{product_name}**\nStatus: {status}",
        'add_photo_button': "➕ Add Photo",
        'change_photo_button': "✏️ Change Photo",
        'delete_photo_button': "🗑️ Delete Photo",
        'back_to_editing_button': "🔙 Back to Editing",
        'cancel_button_3': "🔙 Cancel",
        'send_product_image': "📸 **Send the product image** (or a URL link):",
        'image_deleted': "🗑️ Image deleted!",
        'product_image_management_no_image': "🖼️ **Product Image Management**\n\nStatus: ❌ No image",
        'confirm_delete_product': "🗑️ Are you sure you want to delete **{name}**?",
        'yes_delete_button': "❌ Yes, delete",
        'cancelled': "🚫 Cancelled",
        'product_already_deleted': "❌ Product already deleted",
        'product_deleted': "🗑️ {name} deleted!",
        'use_start': "Use /start for navigating the store! 🛍️",
        'enter_product_description': "📝 <b>Enter product description:</b>",
        'simple_product_button': "📦 Simple Product",
        'has_variants_button': "🎨 Has Variants",
        'choose_product_type': "❓ <b>Choose Product Type:</b>",
        'enter_stock': "🔢 <b>Enter Stock:</b>",
        'invalid_price': "⚠️ <b>Invalid Price!</b>",
        'enter_category': "📂 <b>Enter Category:</b>",
        'invalid_quantity': "⚠️ <b>Invalid quantity!</b>",
        'enter_emoji': "✨ <b>Enter Emoji:</b>",
        'send_photo': "📸 <b>Send Photo:</b>",
        'product_created': "✅ Product <b>{name}</b> created!",
        'back_button_3': "🔙 Back",
        'status_message': "✨ <b>{status_msg}</b>\n\n",
        'select_variant_type': "🎨 <b>Select Variant Type:</b>\n\n{added_info}Select a category or click <b>Finish</b>.",
        'error_handler': "❌ An error has occurred. Please try again or use /start",
        'add_variants_before_finishing': "⚠️ Add variants before finishing!",
        'product_created_2': "✅ <b>{name}</b> created!",
        'welcome_promo_1': "Only 1 step left to complete your profile! ✨",
        'welcome_promo_2': "Almost there! Fill 2 more fields for fast checkout. 🚀",
        'welcome_promo_3': "Your profile is partially filled. Add data for convenience. 📦",
        'welcome_promo_4': "Welcome! Complete your profile to order in one click. 👇",
        'missing_fields_info': "\n{promo}\n⚠️ <b>Please fill:</b> {missing_labels}\n────────────────────",
        'invoice_title': "Order Payment — {shop_name}",
        'invoice_desc': "Payment for items in your cart",
        'invoice_label': "Total Amount",
        'stock_out_error': "Sorry, {name} is out of stock!",
        'method_online_card': "Online Card Payment",
        'method_card_courier': "Card to courier",
        'method_cod': "Cash on delivery",
        'admin_wizard_simple_price': "💰 <b>Step 3: Price</b>\n\nEnter the product price (numbers only).\n<b>Example:</b> <code>1250</code> or <code>45.50</code>",
        'admin_wizard_simple_stock': "🔢 <b>Step 4: Stock</b>\n\nEnter the quantity available.\n<b>Example:</b> <code>100</code>",
        'admin_wizard_variant_photo': "🎨 <b>Step 3: Photo</b>\n\nSend a photo or a direct link.\nIf no photo is needed, send <code>-</code>",
        'error_photo_required': "⚠️ <b>Error: Photo required!</b>\n\nPlease upload an image file or send a direct link (http...).\nIf no photo is needed, type <code>-</code>",
        'variant_format_hint': "✍️ <b>Enter variants in format:</b>\n<code>Option=Qty=Price</code>\n\n<b>Example:</b> <code>XL=10=1500, L=5=1400</code>",
        'admin_ex_Size': "S=10=1200, M=5=1300, L=2=1400",
        'admin_ex_Color': "Red=10=500, Blue=5=550",
        'admin_ex_Memory': "128GB=10=800, 256GB=5=950",
        'admin_ex_Volume': "0.5L=10=50, 1L=20=90",
        'admin_ex_Weight': "1kg=10=100, 5kg=2=450",
        'admin_ex_ShoeSize': "41=5=2500, 42=10=2500",
        'admin_ex_default': "Option=Qty=Price",
        'variant_input_prompt': "📥 <b>Enter options for {v_type}:</b>\n\n<b>Format:</b> <code>Option=Qty=Price</code>\n<b>Example:</b> <code>{example}</code>",
        'back_to_types_btn': "🔙 Back to Types",

        'admin_wizard_variant_title': "🎨 <b>Variant Management</b>\n\n{added_info}Select a variant type to add or click <b>Finish</b>:",
        'active_variant_label': "📍 <b>Active:</b> ",
        'type_Size': "Size",
        'type_Color': "Color",
        'type_Memory': "Memory",
        'type_Volume': "Volume",
        'type_Weight': "Weight",
        'type_ShoeSize': "Shoe Size",

        'admin_img_status_set': "✅ Image set",
        'admin_img_status_none': "❌ No image",
        'admin_variant_type_prompt': "Selected: <b>{variant_type}</b>\n\n⌨️ Enter available options separated by comma.\n\n<b>Formats:</b>\n1. <code>Option=Qty</code> (Default Price)\n2. <code>Option=Qty=Price</code> (Custom Price)\n\n✅ <b>Example for {variant_type}:</b>\n<code>{example_text}</code>",
        'admin_product_created_simple': "✅ Product Created!",
        'admin_category_updated': "✅ Category updated to **{category}**!",
        'admin_stock_details_header': "\n📊 <b>Stock Details:</b>\n",
        'variant_default_format': "Option=Qty=Price",
        'variant_error_title': "⚠️ <b>Format Error for {v_type}!</b>",
        'variant_error_msg': "Please use: <code>Option=Qty=Price</code>",
        'variant_example_label': "<b>Example:</b>",
        # Summary screen
        'summary_title': "🔍 Confirm Your Details",
        'summary_confirm_btn': "✅ All Correct",
        'summary_edit_name_btn': "✏️ Name",
        'summary_edit_email_btn': "✏️ Email",
        'summary_edit_address_btn': "✏️ Shipping",
        'summary_edit_phone_btn': "✏️ Phone",
        'summary_name_label': "👤 Name",
        'summary_email_label': "📧 Email",
        'summary_address_label': "📍 Shipping",
        'summary_phone_label': "📱 Phone",

        # Profile/Checkout validation errors
        'err_invalid_name': "❌ <b>Invalid Name</b>\n\n<b>Example:</b> <i>John Doe</i>\n\nPlease try again:",
        'err_invalid_email': "❌ <b>Invalid Email Format</b>\n\n<b>Example:</b> <i>user@example.com</i>\n\nPlease try again:",
        'err_invalid_phone': "❌ <b>Invalid Phone Number</b>\n\n<b>Example:</b> <i>+1234567890</i>\n\nPlease try again:",
        'err_invalid_address': "❌ <b>Address too short</b>\n\n<b>Example:</b> <i>Germany, Berlin, Hauptstraße 10, 10115</i>\n\nPlease try again:",

        # Edit field screen (checkout)
        'edit_field_title': "✏️ Editing: {field}",
        'current_value_label': "Current value:",
        'example_label': "Example:",
        'back_to_summary_btn': "🔙 Back to Summary",
        'enter_new_value_prompt': "Please enter the new value below:",
    }
}